name: eliud_stl_mona
description:  Mona style package

version: 1.0.0

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  flutter_colorpicker: 1.0.3
  google_fonts: ^2.1.0

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
