---
name: eliud_stl_mona
description: eliud_stl_mona is a style which can be used for your eliud app. More
  info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_stl_mona
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  delayed_display: ^2.0.0
  google_fonts: ^6.2.1
  split_view: ^3.2.1
  eliud_core: ^1.3.0
  eliud_stl_mona_model: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_model: ^1.3.0
  flutter_colorful_tab: ^0.1.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
