---
name: eliud_stl_mona
description: Mona style package
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_stl_mona
version: 1.0.7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter_colorpicker: ^1.0.3
  split_view: ^3.2.1
  eliud_core: ^1.0.14
  delayed_display: ^2.0.0
  transparent_image: ^2.0.0
  google_fonts: ^4.0.4
  flutter_colorful_tab: ^0.1.0
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  equatable: ^2.0.5
  cloud_firestore: ^4.6.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  meta: ^1.8.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.6
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
